<?php

namespace {

    use SilverStripe\AssetAdmin\Forms\UploadField;
    use SilverStripe\Assets\Image;
    use SilverStripe\CMS\Model\SiteTree;
    use SilverStripe\Forms\CheckboxField;
    use SilverStripe\Forms\DropdownField;
    use SilverStripe\Forms\HiddenField;
    use SilverStripe\Forms\HTMLEditor\HTMLEditorField;
    use SilverStripe\Forms\ReadonlyField;
    use SilverStripe\Forms\TextField;
    use SilverStripe\ORM\DataObject;

    class CarouselItem extends DataObject
    {
        private static $default_sort  = 'Sort';

        private static $db = [
            'Name'     => 'Varchar',
            'Content'  => 'HTMLText',
            'Icon'     => 'Text',
            'Archived' => 'Boolean',
            'Sort'     => 'Int'
        ];

        private static $has_one = [
            'Parent' => Carousel::class,
            'Image'  => Image::class,
            'Page'   => SiteTree::class
        ];

        private static $owns = [
            'Image',
        ];

        private static $summary_fields = [
            'Name',
            'Icon',
            'Image.CMSThumbnail' => 'Image',
            'Status'
        ];

        public function getCMSFields()
        {
            $fields = parent::getCMSFields(); // TODO: Change the autogenerated stub
            $fields->removeByName('ParentID');
            $fields->addFieldToTab('Root.Main', ReadonlyField::create('ParentRO', 'Parent', $this->Parent()->Name));

            $fields->addFieldToTab('Root.Main', TextField::create('Name'));
            $fields->addFieldToTab('Root.Main', TextField::create('Icon', 'Fontawesome Icon')
                ->setRightTitle('E.g fab fa-twitter')
                ->setDescription('Click<a href="https://fontawesome.com/icons?d=gallery">&nbsp;here&nbsp;</a> to search for more icons <a href="https://fontawesome.com/icons?d=gallery">&nbsp;@fontawesome.com</a>'));
            $fields->addFieldToTab('Root.Main', UploadField::create('Image', 'Featured Image')->setFolderName('Carousel_Images'));
            $fields->addFieldToTab('Root.Main', DropdownField::create('PageID', 'Select page to link', SiteTree::get()->map('ID','Title'))
                ->setEmptyString('(Select one)'));
            $fields->addFieldToTab('Root.Main', HTMLEditorField::create('Content'));
            $fields->addFieldToTab('Root.Main', CheckboxField::create('Archived'));
            $fields->addFieldToTab('Root.Main', HiddenField::create('Sort'));

            return $fields;
        }

        public function getStatus()
        {
            if($this->Archived == 1) return _t('GridField.Archived', 'Archived');
            return _t('GridField.Live', 'Live');
        }
    }
}
