<?php

namespace {

    use SilverStripe\AssetAdmin\Forms\UploadField;
    use SilverStripe\Assets\Image;
    use SilverStripe\Forms\CheckboxField;
    use SilverStripe\Forms\HiddenField;
    use SilverStripe\Forms\ReadonlyField;
    use SilverStripe\Forms\TextField;
    use SilverStripe\ORM\DataObject;

    class LogoItem extends DataObject
    {
        private static $default_sort = 'Sort ASC';

        private static $db = [
            'Name'       => 'Text',
            'WebsiteURL' => 'Text',
            'Archived'   => 'Boolean',
            'Sort'       => 'Int',
        ];

        private static $has_one = [
            'Parent'    => Footer::class,
            'LogoImage' => Image::class,
        ];

        private static $owns = [
            'LogoImage'
        ];

        private static $summary_fields = [
            'Name',
            'LogoImage.CMSThumbnail' => 'Logo Image',
            'WebsiteURL' => 'External URL',
            'Status'
        ];

        public function getCMSFields()
        {
            $fields = parent::getCMSFields(); // TODO: Change the autogenerated stub
            $fields->removeByName('ParentID');
            $fields->addFieldToTab('Root.Main', ReadonlyField::create('ParentRO', 'Parent', $this->Parent()->Name));

            $fields->addFieldToTab('Root.Main', TextField::create('Name'));
            $fields->addFieldToTab('Root.Main', UploadField::create('LogoImage')
                ->setFolderName('Logo'));
            $fields->addFieldToTab('Root.Main', TextField::create('WebsiteURL','External Url'));
            $fields->addFieldToTab('Root.Main', CheckboxField::create('Archived'));
            $fields->addFieldToTab('Root.Main', HiddenField::create('Sort'));

            return $fields;
        }

        public function getStatus()
        {
            if($this->Archived == 1) return _t('GridField.Archived', 'Archived');
            return _t('GridField.Live', 'Live');
        }
    }
}
