<?php

namespace {

    use SilverStripe\Forms\CheckboxField;
    use SilverStripe\Forms\HiddenField;
    use SilverStripe\Forms\HTMLEditor\HTMLEditorField;
    use SilverStripe\Forms\ReadonlyField;
    use SilverStripe\Forms\TextField;
    use SilverStripe\ORM\DataObject;

    class TextIconItem extends DataObject
    {
        private static $default_sort  = 'Sort';

        private static $db = [
            'Name'     => 'Text',
            'Content'  => 'HTMLText',
            'Icon'     => 'Text',
            'Archived' => 'Boolean',
            'Sort'     => 'Int'
        ];

        private static $has_one = [
            'Parent' => TextWithIcon::class,
        ];

        private static $summary_fields = [
            'Name',
            'Content',
            'Icon',
            'Status'
        ];

        public function getCMSFields()
        {
            $fields = parent::getCMSFields(); // TODO: Change the autogenerated stub
            $fields->removeByName('ParentID');
            $fields->addFieldToTab('Root.Main', ReadonlyField::create('ParentRO', 'Parent', $this->Parent()->Name));

            $fields->addFieldToTab('Root.Main', TextField::create('Name'));
            $fields->addFieldToTab('Root.Main', HTMLEditorField::create('Content'));
            $fields->addFieldToTab('Root.Main', TextField::create('Icon', 'Fontawesome Icon')
                ->setRightTitle('E.g. fab fa-twitter')
                ->setDescription('Click<a href="https://fontawesome.com/icons?d=gallery">&nbsp;here&nbsp;</a> to search for more icons <a href="https://fontawesome.com/icons?d=gallery">&nbsp;@fontawesome.com</a>'));
            $fields->addFieldToTab('Root.Main', CheckboxField::create('Archived'));
            $fields->addFieldToTab('Root.Main', HiddenField::create('Sort'));

            return $fields;
        }

        public function getStatus()
        {
            if($this->Archived == 1) return _t('GridField.Archived', 'Archived');
            return _t('GridField.Live', 'Live');
        }
    }
}
