<?php

namespace {

    use SilverStripe\ORM\DB;

    class LoginPage extends Page {

        private static $icon_class = 'font-icon-torso';

        public function requireDefaultRecords()
        {
            parent::requireDefaultRecords(); // TODO: Change the autogenerated stub

            if (!self::get()->first())
            {
                $page = self::create();
                $page->Title = 'Login';
                $page->URLSegment = 'login';
                $page->MenuTitle = 'Login';
                $page->ShowInMenus = false;
                $page->Content = 'You can populate this text from the CMS';
                $page->write();
                DB::alteration_message('Default login page has been created');
            }
        }
    }
}
