<?php

namespace {

    use SilverStripe\Security\Group;
    use SilverStripe\Security\Security;

    class AdminPageController extends PageController {

        protected function init()
        {
            parent::init(); // TODO: Change the autogenerated stub

            $member = $this->getCurrentUser();
            $controller = new PageController();

            if ($member) {
                $adminGroup = Group::get()->filter('Code', 'administrators');
                if($adminGroup->Count() > 0){
                    $adminGroup = $adminGroup->first();
                }

                if (!$member->inGroup($adminGroup)) {
                    return $this->redirect('dashboard');
                }
            } else {
                return $this->redirect('login');
            }
        }

        public function getAllVisibleModules()
        {
            return Modules::get()->filter('Archived', false);
        }

        public function getAllVisibleMemberType()
        {
            return MemberType::get()->filter('Archived', false);
        }

        public function getAllVisibleSubmissions()
        {
            return Submissions::get()->filter('Archived', false);
        }

        public function getCurrentUser()
        {
            return Security::getCurrentUser();
        }
    }
}
