<?php

namespace {

    use SilverStripe\Security\Security;

    class DashboardPageController extends PageController
    {
        protected function init()
        {
            parent::init(); // TODO: Change the autogenerated stub

            $member = $this->getCurrentUser();
            if (!$member) {
                return $this->redirect('login');
            }
        }

        public function getCurrentUser()
        {
            return Security::getCurrentUser();
        }

        public function getShowDashboard()
        {
            $member = $this->getCurrentUser();
            if ($member) {
                if ($member->ClinicalModuleID) {
                    return FieldTypeHolder::get()->filter(['ModuleID' => $member->ClinicalModuleID, 'Archived' => false]);
                } else {
                    if ($member->PrescribingIndicatorID) {
                        return FieldTypeHolder::get()->filter(['ModuleID' => $member->PrescribingIndicatorID, 'Archived' => false]);
                    }
                }
            }
            return 'No current module/s';
        }
    }
}
