<?php

namespace {

    use SilverStripe\Security\Security;
    use SilverStripe\View\Requirements;

    class DashboardPageController extends PageController
    {
        protected function init()
        {
            parent::init(); // TODO: Change the autogenerated stub

            Requirements::css('https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.css');
            Requirements::javascript('//code.jquery.com/ui/1.12.1/jquery-ui.js');
            Requirements::javascript('https://cdn.jsdelivr.net/momentjs/latest/moment.min.js');
            Requirements::javascript('https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js');
            Requirements::javascript('https://cdn.datatables.net/1.10.23/js/jquery.dataTables.min.js');

            $member = $this->getCurrentUser();
            if (!$member) {
                return $this->redirect('login');
            }
        }

        public function getCurrentUser()
        {
            return Security::getCurrentUser();
        }

        public function getShowDashboard()
        {
            $member = $this->getCurrentUser();
            if ($member) {
                if ($member->ClinicalModuleID) {
                    return FieldTypeHolder::get()->filter(['ModuleID' => $member->ClinicalModuleID, 'Archived' => false]);
                } else {
                    if ($member->PrescribingIndicatorID) {
                        return FieldTypeHolder::get()->filter(['ModuleID' => $member->PrescribingIndicatorID, 'Archived' => false]);
                    }
                }
            }
            return 'No current module/s';
        }
    }
}
