<?php

namespace {

    use SilverStripe\Forms\CheckboxField;
    use SilverStripe\Forms\GridField\GridField;
    use SilverStripe\Forms\GridField\GridFieldConfig_RecordEditor;
    use SilverStripe\Forms\HiddenField;
    use SilverStripe\Forms\ReadonlyField;
    use SilverStripe\Forms\TextField;
    use SilverStripe\ORM\DataObject;
    use Symbiote\GridFieldExtensions\GridFieldEditableColumns;
    use Symbiote\GridFieldExtensions\GridFieldOrderableRows;

    class Records extends DataObject
    {
        private static $singular_name = 'Record';

        private static $plural_name = 'Records';

        private static $default_sort = 'Sort';

        private static $table_name = 'Records';

        private static $db = [
            'Name'     => 'Text',
            'Archived' => 'Boolean',
            'Sort'     => 'Int'
        ];

        private static $has_one = [
            'Submission' => Submissions::class
        ];

        private static $has_many = [
            'Responses' => Responses::class
        ];

        private static $summary_fields = [
            'ID',
            'Name',
            'Status'
        ];

        public function getCMSFields()
        {
            $fields = parent::getCMSFields(); // TODO: Change the autogenerated stub
            $fields->removeByName('SubmissionID');
            $fields->addFieldToTab('Root.Main', ReadonlyField::create('SubmissionRO', 'Submission', $this->Submission()->Title));

            $fields->addFieldToTab('Root.Main', new TextField('Name'));

            $gridConfig = GridFieldConfig_RecordEditor::create(999);
            if($this->owner->Responses()->Count())
            {
                $gridConfig->addComponent(new GridFieldOrderableRows());
            }
            $gridConfig->addComponent(new GridFieldEditableColumns());
            $gridColumns = $gridConfig->getComponentByType(GridFieldEditableColumns::class);
            $gridColumns->setDisplayFields([
                'Archived' => [
                    'title' => 'Archive',
                    'callback' => function($record, $column, $grid) {
                        return CheckboxField::create($column);
                    }]
            ]);

            $gridField = GridField::create(
                'Responses',
                'Responses',
                $this->owner->Responses(),
                $gridConfig
            );

            $fields->removeByName('Responses');
            $fields->addFieldToTab('Root.Main', $gridField);

            $fields->addFieldToTab('Root.Main', new CheckboxField('Archived'));
            $fields->addFieldToTab('Root.Main', new HiddenField('Sort'));

            return $fields;
        }

        public function getStatus()
        {
            if($this->Archived == 1) return _t('GridField.Archived', 'Archived');
            return _t('GridField.Live', 'Live');
        }
    }
}
