<?php

namespace {

    use SilverStripe\Forms\CheckboxField;
    use SilverStripe\Forms\GridField\GridField;
    use SilverStripe\Forms\GridField\GridFieldConfig_RecordEditor;
    use SilverStripe\Forms\HiddenField;
    use SilverStripe\Forms\ReadonlyField;
    use SilverStripe\Forms\TextareaField;
    use SilverStripe\Forms\TextField;
    use SilverStripe\ORM\DataObject;
    use Symbiote\GridFieldExtensions\GridFieldEditableColumns;
    use Symbiote\GridFieldExtensions\GridFieldOrderableRows;

    class Responses extends DataObject
    {
        private static $default_sort = 'Sort';

        private static $db = [
            'Name'       => 'Text',
            'Response'   => 'Text',
            'Identifier' => 'Int',
            'Archived'   => 'Boolean',
            'Sort'       => 'Int'
        ];

        private static $has_one = [
            'Record' => Records::class
        ];

        private static $has_many = [
            'SubResponses' => SubResponses::class,
        ];

        private static $summary_fields = [
            'Name' => 'Label',
            'Response',
            'Status',
        ];

        public function getCMSFields()
        {
            $fields = parent::getCMSFields(); // TODO: Change the autogenerated stub
            $fields->removeByName('RecordID');
            $fields->addFieldToTab('Root.Main', ReadonlyField::create('RecordRO', 'Record', $this->Record()->Title));

            $fields->addFieldToTab('Root.Main', new TextareaField('Name', 'Label'));
            $fields->addFieldToTab('Root.Main', new TextField('Response'));

            $gridConfig = GridFieldConfig_RecordEditor::create(999);
            if($this->owner->SubResponses()->Count())
            {
                $gridConfig->addComponent(new GridFieldOrderableRows());
            }
            $gridConfig->addComponent(new GridFieldEditableColumns());
            $gridColumns = $gridConfig->getComponentByType(GridFieldEditableColumns::class);
            $gridColumns->setDisplayFields([
                'Archived' => [
                    'title' => 'Archive',
                    'callback' => function($record, $column, $grid) {
                        return CheckboxField::create($column);
                    }]
            ]);

            $gridField = GridField::create(
                'SubResponses',
                'Sub Responses',
                $this->owner->SubResponses(),
                $gridConfig
            );

            $fields->removeByName('SubResponses');
            $fields->addFieldToTab('Root.Main', $gridField);

            $fields->addFieldToTab('Root.Main', new TextField('Identifier'));
            $fields->addFieldToTab('Root.Main', new CheckboxField('Archived'));
            $fields->addFieldToTab('Root.Main', new HiddenField('Sort'));

            return $fields;
        }

        public function getVisibleSubResponses()
        {
            return $this->SubResponses()->filter('Archived', false)->sort('Sort');
        }

        public function getStatus()
        {
            if($this->Archived == 1) return _t('GridField.Archived', 'Archived');
            return _t('GridField.Live', 'Live');
        }
    }
}
