<?php

namespace {

    use SilverStripe\Forms\CheckboxField;
    use SilverStripe\Forms\DropdownField;
    use SilverStripe\Forms\HiddenField;
    use SilverStripe\Forms\ReadonlyField;
    use SilverStripe\Forms\TextField;
    use SilverStripe\ORM\DataObject;
    use UncleCheese\DisplayLogic\Forms\Wrapper;

    class MultiTextboxItem extends DataObject
    {
        private static $default_sort = 'Sort';
        private static $table_name = 'MultiTextboxItem';

        private static $singular_name = "Multiple textbox item";
        private static $plural_name = "Multiple textbox items";

        private static $db = [
            'Name'     => 'Varchar',
            'Type'     => 'Varchar',
            'CompareType' => 'Text',
            'Archived' => 'Boolean',
            'Sort'     => 'Int'
        ];

        private static $has_one = [
            'FieldType' => FieldType::class
        ];

        private static $summary_fields = [
            'Name',
            'CompareType',
            'Status'
        ];

        public function getCMSFields()
        {
            $fields = parent::getCMSFields(); // TODO: Change the autogenerated stub
            $fields->removeByName('FieldTypeID');
            $fields->addFieldToTab('Root.Main', ReadonlyField::create('FieldTypeRO', 'Field type', $this->FieldType()->Name));
            $fields->addFieldToTab('Root.Main', TextField::create('Name'));
            $fields->addFieldToTab('Root.Main', DropdownField::create('Type', 'Textbox type',
                array(
                    'text'   => 'Text',
                    'number' => 'Number',
                    'compare'=> 'Number comparison',
                )));

            $fields->addFieldToTab('Root.Main', DropdownField::create('CompareType', 'Comparison type',
                array(
                    'isGreaterThan' => 'Greater than',
                    'isLessThan'    => 'Less than'
                ))->displayIf("Type")->isEqualTo("compare")->end());

            $fields->addFieldToTab('Root.Main', CheckboxField::create('Archived'));
            $fields->addFieldToTab('Root.Main', HiddenField::create('Sort'));

            return $fields;
        }

        public function getStatus()
        {
            if($this->Archived == 1) return _t('GridField.Archived', 'Archived');
            return _t('GridField.Live', 'Live');
        }
    }
}
